# Use official PHP + Apache image
FROM php:8.2-apache

# Enable Apache mod_rewrite for clean URLs
RUN a2enmod rewrite

# Copy project into server directory
COPY . /var/www/html/

# Set working directory
WORKDIR /var/www/html/

# Permissions fix (important)
RUN chown -R www-data:www-data /var/www/html/

# Expose HTTP port
EXPOSE 80
